### PR TITLE
prepared query: add missing RemoveEmptyTag and Name should be optional

### PR DESCRIPTION
**Pull request by ygersie**
* The Name field of the JSON payload should be optional, see:
    https://www.consul.io/api-docs/query#name
  * Add missing https://www.consul.io/api-docs/query#removeemptytags

### CODE REVIEW

**Comment by remilapeyre** [comment]
Hi @ygersie, thanks for opening this PR. The API client will first need to be updated at https://github.com/hashicorp/consul before I can merge this. I will look into this.

**Comment by remilapeyre** [comment]
Hi @ygersie! I opened https://github.com/hashicorp/consul/pull/14244 to add this to the Consul API client. Once it is merge we will be able to add support for this in the provider.

**Review by dhiaayachi — APPROVED** [review]
LGTM!

**Comment by ygersie** [comment]
@remilapeyre is there any chance this can get a push?

**Comment by LukasdeBoer** [comment]
Looks like the required changes got merged in https://github.com/hashicorp/consul/pull/16113, I think this should now be doable :) 
@remilapeyre

**Review by remilapeyre — APPROVED** [review]
Hi @ygersie, thanks for taking the time to make this Pull Request! It will ship in the next release :)

**Pull request merged**
